### ISSUE TITLE
update official repos (pypi and conda)

### ISSUE THREAD

**Issue by tomcucinotta** [peterwittek/somoclu#161]
Hi,
how can we get official repos (pypi and conda) updated with the latest somoclu ?

For example, pypi is stuck at April 2020:
  https://pypi.org/project/somoclu/
which is probably the same as with conda:
  https://anaconda.org/conda-forge/somoclu

Thanks!

**Comment by xgdgsc** [comment]
I would like to do a pypi (which I have access) upload github workflow later. For now you can download the python wheel artifact from actions https://github.com/peterwittek/somoclu/actions/runs/934236645 .

 The conda repo is not accessible for me since the repo owner had died from an accident and I don' t know if there' s a mechanism for ownership transfer. 

Maybe you can follow https://github.com/peterwittek/somoclu/blob/master/.github/workflows/u2004.yml to create a new workflow that builds the artifact for conda (or other python versions that may interest you).

**Comment by xgdgsc** [comment]
Sorry for the expiration of github actions artifacts. Just made a new release saving all files here: https://github.com/peterwittek/somoclu/releases/tag/1.7.6
