### ISSUE TITLE
Request for cosine distance

### ISSUE THREAD

**Issue by ajallooeian** [peterwittek/somoclu#30]
Hi,

I have been using somoclu for a week now and really enjoying it. I would appreciate it if cosine distance is also implemented, as it is useful for many document matching application.

Thanks,
Mos

**Comment by peterwittek** [comment]
We routinely use Somoclu in text mining and it makes little sense to implement the cosine distance because it is almost identical to the Euclidean, as long as your data instances are normalized. Take two vectors, x and y. Then (d(x,y))^2=sum_k (x_k-y_k)^2 = |x|^2+|y|^2 - 2(x,y). Since |x|^2=|y|^2=1, this is just 2(1-(x,y)), so a separate cosine distance would result in the exact same topology.

**Comment by ajallooeian** [comment]
Thanks a lot for this to-the-point explanation. :)
